# 202001549 장희권

In [20]:
import numpy as np

In [21]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[5]

5

In [23]:
arr[5:8]

array([5, 6, 7])

In [24]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [25]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [26]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [27]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [28]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [29]:
arr2d[0][2]

3

In [30]:
arr2d[0, 2]

3

In [31]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
arr3d[1,0]

array([7, 8, 9])

In [36]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [37]:
x[0]

array([7, 8, 9])

In [38]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [39]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [40]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [43]:
arr2d[1, :2]

array([4, 5])

In [44]:
arr2d[:2, 2]

array([3, 6])

In [45]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [46]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# 202001549 장희권