# 202001549 장희권

In [4]:
import numpy as np

In [5]:
arr = np.arange(15).reshape((3, 5))

In [6]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [8]:
arr = np.random.randn(6, 3)

In [9]:
arr

array([[ 1.5172536 ,  0.14857198,  0.38632774],
       [-0.02101945, -1.86499172, -0.02626018],
       [-0.43108909, -0.15771202,  1.15634283],
       [-1.07298901,  0.18177092, -0.57985141],
       [ 0.20942053,  0.44511474, -0.45219488],
       [-1.89337839, -0.19819997,  0.55861489]])

In [10]:
np.dot(arr.T, arr)

array([[ 7.2683822 ,  0.60605591, -0.4419717 ],
       [ 0.60605591,  3.79559188, -0.49339286],
       [-0.4419717 , -0.49339286,  2.33982591]])

In [11]:
arr = np.arange(16).reshape((2, 2, 4))

In [12]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [13]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [14]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [15]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 202001549 장희권