# 202001549 장희권

In [1]:
import numpy as np

In [2]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [3]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [4]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [5]:
arr = np.random.randn(4, 4)
arr

array([[-0.75027877, -1.379144  , -1.67788156, -1.19136859],
       [-0.57448848,  0.60429781,  0.01438718,  0.46747908],
       [-0.8177113 ,  0.0723959 ,  0.81988293, -0.08184146],
       [-2.15640816, -1.6857159 ,  0.07975983,  0.32022184]])

In [6]:
arr > 0

array([[False, False, False, False],
       [False,  True,  True,  True],
       [False,  True,  True, False],
       [False, False,  True,  True]])

In [7]:
np.where(arr > 0, 2, -2)

array([[-2, -2, -2, -2],
       [-2,  2,  2,  2],
       [-2,  2,  2, -2],
       [-2, -2,  2,  2]])

In [8]:
np.where(arr > 0, 2, arr)

array([[-0.75027877, -1.379144  , -1.67788156, -1.19136859],
       [-0.57448848,  2.        ,  2.        ,  2.        ],
       [-0.8177113 ,  2.        ,  2.        , -0.08184146],
       [-2.15640816, -1.6857159 ,  2.        ,  2.        ]])

# 202001549 장희권