# 202001549 장희권

In [2]:
import numpy as np

In [3]:
arr = np.random.randn(4, 4)

In [4]:
arr

array([[ 0.35121357,  0.82325467,  0.47328674, -0.35985512],
       [ 1.04514629, -1.90372666, -1.10871606, -0.00557721],
       [-0.84342341,  0.13608683,  1.40483945,  1.38949899],
       [ 0.03140916,  1.86391477,  1.89788737,  0.18492436]])

In [5]:
row_means = arr.mean(1)

In [6]:
row_means.shape

(4,)

In [7]:
row_means.reshape((4, 1))

array([[ 0.32197496],
       [-0.49321841],
       [ 0.52175047],
       [ 0.99453391]])

In [8]:
dewaned = arr - row_means.reshape((4, 1))

In [9]:
dewaned.mean(1)

array([ 0.00000000e+00, -2.77555756e-17,  0.00000000e+00,  0.00000000e+00])

# 202001549 장희권