# 202001549 장희권

In [1]:
import numpy as np

In [3]:
arr = np.zeros((4, 3))

In [4]:
arr[:] = 5

In [5]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [8]:
col = np.array([1.28, -0.42, 0.44, 1.6])

In [9]:
arr[:] = col[:, np.newaxis]

In [10]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [11]:
arr[:2] = [[-1.37], [0.509]]

In [12]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

# 202001549 장희권