# 202001549 장희권

In [10]:
import numpy as np

In [11]:
arr = np.zeros((4, 4))

In [12]:
arr_3d = arr[:, np.newaxis, :]

In [13]:
arr_3d.shape

(4, 1, 4)

In [14]:
arr_1d = np.random.normal(size=3)

In [15]:
arr_1d[:, np.newaxis]

array([[ 0.0591146 ],
       [-1.23364018],
       [ 0.73761316]])

In [16]:
arr_1d[np.newaxis, :]

array([[ 0.0591146 , -1.23364018,  0.73761316]])

In [26]:
arr = np.random.randn(3, 4, 5)

In [27]:
depth_means = arr.mean(2)

In [28]:
depth_means

array([[ 0.36714376, -0.19299852, -0.59109261,  0.38478365],
       [ 0.89256115, -0.46728999, -0.52879117, -0.36946798],
       [-0.24658652,  0.70280005,  0.57376486,  0.16460737]])

In [29]:
depth_means.shape

(3, 4)

In [30]:
demeanded = arr - depth_means[:,:,np.newaxis]

In [31]:
demeanded

array([[[-1.17043139,  1.37401724, -0.14515767,  0.40066025,
         -0.45908843],
        [ 0.22469052,  0.85120497, -0.98836582, -0.61559203,
          0.52806236],
        [-0.28818145,  0.04602846, -0.92257848,  0.50551465,
          0.65921683],
        [-0.76298896, -0.07011666,  0.48969609,  0.2364906 ,
          0.10691893]],

       [[-1.00036979, -0.19127022,  2.39369979, -2.92571485,
          1.72365507],
        [-0.41603719, -0.21227401, -0.59213238,  1.4699269 ,
         -0.24948332],
        [-0.09035997, -0.95455989,  0.41758164,  0.13579389,
          0.49154433],
        [ 0.73332331, -0.5739508 , -0.66305913, -0.66106638,
          1.164753  ]],

       [[ 2.43972563,  0.40155701, -1.95119177, -0.42346004,
         -0.46663083],
        [ 0.38852045, -1.40847455, -0.10753483,  0.17816869,
          0.94932023],
        [ 0.13511896,  0.84034308, -0.81458171, -0.99468628,
          0.83380595],
        [ 1.09823502,  0.30893008,  0.30937428, -0.85037539,
         -0

# 202001549 장희권